### ISSUE TITLE
Falta import no 'fastapi-example'

### ISSUE THREAD

**Issue by thomascenni** [Leothi/fastapi-example#1]
Interessante exemplo!
Usando o docker-compose, as imagens do mongodb e mongo-express estao rodando normalmente, mas o fastapi-example tem algum problema de import, segue log:

```
Traceback (most recent call last):,
...
  File "/usr/local/lib/python3.6/dist-packages/api/modules/usuario.py", line 3, in <module>,
    from api.database.default.sql_alchemy.connector import Connector,
  File "/usr/local/lib/python3.6/dist-packages/api/database/__init__.py", line 5, in <module>,
    from api.settings import envs,
  File "/usr/local/lib/python3.6/dist-packages/api/settings.py", line 4, in <module>,
    from api.utils.logger import DEFAULT_FORMAT,
ModuleNotFoundError: No module named 'api.utils',
```

![Screen Shot 2020-12-30 at 15 26 52](https://user-images.githubusercontent.com/33039107/103373289-490b2280-4ab3-11eb-9279-332c12ea988b.png)

Obrigado!

**Comment by Leothi** [comment]
Obrigado por verificar!

Tinha esquecido de dar push no commit (243da9d3627d5638dd79e10864373080ab18e8be) com a correção nos volumes do docker-compose.

Acredito que esteja resolvido.
